/** Build the same Tailwind utilities previously generated by the CDN. */
export default {
  content: ['./index.html', './App.tsx', './components/**/*.{ts,tsx}', './data/**/*.ts'],
  theme: { extend: {} },
  plugins: []
};
